=== AutoKMG/Web-Technologies-Lab/Week 6 Lab/joke-schema.json
{
    "$schema":"http://json-schema.org/draft-07/schema",
    "title":"Schema for joke",
    "type":"object",
    "properties": {
        "categories":{"$ref": "./categories-schema.json"},
        "created_at":{"type":"string"},
        "icon_url":{"const":"https://assets.chucknorris.host/img/avatar/chuck-norris.png"},
        "id": {"type":"string"},
        "updated_at":{"type":"string"},
        "url":{"type":"string","format": "url"},
        "value":{"type":"string"}
    },
    "required":[
        "categories",
        "created_at",
        "icon_url",
        "id",
        "updated_at",
        "url",
        "value"
    ],
    "additionalProperties": false
}

=== AutoKMG/Web-Technologies-Lab/Week 6 Lab/joke.json
{
    "categories": [],
    "created_at": "2020-01-05 13:42:26.766831",
    "icon_url": "https://assets.chucknorris.host/img/avatar/chuck-norris.png",
    "id": "24v13bMAQ7-eEs-1TMw9Aw",
    "updated_at": "2020-01-05 13:42:26.766831",
    "url": "https://api.chucknorris.io/jokes/24v13bMAQ7-eEs-1TMw9Aw",
    "value": "Chuck Norris once milked a honey badger."
}
